// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdGztbC-mZZ0qJZzXkJFKbAPPO1JS1yhI',
    appId: '1:232014993534:web:1b41f31342dc7cffc5602f',
    messagingSenderId: '232014993534',
    projectId: 'firestore-flutter-4a2ab',
    authDomain: 'firestore-flutter-4a2ab.firebaseapp.com',
    storageBucket: 'firestore-flutter-4a2ab.appspot.com',
    measurementId: 'G-HL3JYRC3VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2U2UKtb-oxcn_xsjVTTDtsbWWna7YKn8',
    appId: '1:232014993534:android:3be75f44ed988ed9c5602f',
    messagingSenderId: '232014993534',
    projectId: 'firestore-flutter-4a2ab',
    storageBucket: 'firestore-flutter-4a2ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTN10wy09Iv1FWIVu2WlY_5x_zDqK6bEI',
    appId: '1:232014993534:ios:cf992e393a843743c5602f',
    messagingSenderId: '232014993534',
    projectId: 'firestore-flutter-4a2ab',
    storageBucket: 'firestore-flutter-4a2ab.appspot.com',
    iosBundleId: 'com.example.flutterFirestoreCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTN10wy09Iv1FWIVu2WlY_5x_zDqK6bEI',
    appId: '1:232014993534:ios:cf992e393a843743c5602f',
    messagingSenderId: '232014993534',
    projectId: 'firestore-flutter-4a2ab',
    storageBucket: 'firestore-flutter-4a2ab.appspot.com',
    iosBundleId: 'com.example.flutterFirestoreCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdGztbC-mZZ0qJZzXkJFKbAPPO1JS1yhI',
    appId: '1:232014993534:web:0dd4a92058a609bfc5602f',
    messagingSenderId: '232014993534',
    projectId: 'firestore-flutter-4a2ab',
    authDomain: 'firestore-flutter-4a2ab.firebaseapp.com',
    storageBucket: 'firestore-flutter-4a2ab.appspot.com',
    measurementId: 'G-DZC6L82C1Y',
  );
}
